### ISSUE TITLE
テーマファイルのみにする

### ISSUE THREAD

**Issue by hideokamoto** [littlebirdjp/tsumugi#1]
リポジトリの中身をテーマファイルのみにしておくと、
再申請や今後のアップデート時の申請の時に
https://github.com/littlebirdjp/tsumugi/archive/master.zip
でDLできるZIPファイルをそのまま使えるので便利です。

ドキュメント系はWikiに引っ越しさせておくといいかもです。

**Comment by youthkee** [comment]
同様のご指摘いただいたので、リポジトリの中身は整理したいと思います！
まるっとzipで落とせるという利点もあるんですね・・。

**Comment by youthkee** [comment]
リポジトリの中身をテーマファイルのみに変更しました。

masterには制作用のファイルも含まれていますが、
テーマファイルのみの配布版をreleaseブランチにアップするようにしてあります。

ドキュメントの移行については、また追って検討しますね。

**Comment by youthkee** [comment]
@hideokamoto 遅くなりましたが、README以外のドキュメントをWikiの方に移行しました！
こちらでいったんクローズとさせていただきます。
